export const styles = {
  container: {
    maxWidth: "1400px",
    margin: "0px auto",
    display: "flex",
    flexDirection: "column",
    paddingBottom: "40px",
    minHeight: "calc(100vh - 20px)",
  },
  headerContiner: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    flex: 1,
    flexGrow: 0.08,
    backgroundColor: "#B8E1FF",
    maxHeight: "80px",
  },
  content: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    margin: "20px 0px 0px 20px",
  },
  circleContainer: {
    display: "flex",
    padding: "10px 0px 10px 25px",
  },
  optionsContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    flex: 0.1,
  },
  contentContainer: {
    display: "flex",
    flexDirection: "row",
    flex: 0.9,
    border: "1px solid black",
  },
  optionsButton: (active = false) => ({
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    backgroundColor: active ? "#8B95C9" : "#D6EDFF",
    border: "none",
    borderRight: "2px solid #ACD7EC",
  }),
  customRadioButton: {
    height: "32px",
    borderRadius: "50%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    position: "relative",
    backgroundColor: "#D6EDFF",
  },
  checkmark: (active) => ({
    width: "25px",
    height: "25px",
    borderRadius: "50%",
    display: "inline-block",
    transition: "background-color 0.3s ease",
    backgroundColor: active ? "#8B95C9" : "#D6EDFF",
    border: `2px solid ${active ? "#D6EDFF" : "#8B95C9"}`,
    padding: active ? "1px" : "3px",
    top: 0,
    left: 0,
  }),
  contentTitle: {
    fontSize: "25px",
    fontWeight: "bold",
    padding: 0,
    margin: 0,
  },
  link: {
    display: "flex",
    flex: 1,
    textDecoration: "none",
  },
  content: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  message: {
    fontSize: "30px",
    fontWeight: "bold",
  },
};
