export const styles = {
  optionsButton: (active = false) => ({
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    backgroundColor: active ? "#8B95C9" : "#D6EDFF",
    border: "none",
    borderRight: "2px solid #ACD7EC",
  }),
  customRadioButton: {
    height: "32px",
    borderRadius: "50%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    position: "relative",
    backgroundColor: "#D6EDFF",
  },
  checkmark: (active) => ({
    width: "25px",
    height: "25px",
    borderRadius: "50%",
    display: "inline-block",
    transition: "background-color 0.3s ease",
    backgroundColor: active ? "#8B95C9" : "#D6EDFF",
    border: `2px solid ${active ? "#D6EDFF" : "#8B95C9"}`,
    padding: active ? "1px" : "3px",
    top: 0,
    left: 0,
  }),
  link: {
    display: "flex",
    flex: 1,
    textDecoration: "none",
  },
};
